# Generated by Django 4.0.3 on 2022-04-08 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_order_shipping_fee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=252)),
                ('discount', models.FloatField()),
                ('discount_type', models.CharField(choices=[('shipping', 'shipping'), ('product', 'product'), ('order', 'order')], max_length=50)),
                ('is_enabled', models.BooleanField()),
            ],
        ),
    ]
