version: '3'

services:

  db:
    image: "postgres:14.2-alpine"
    container_name: "db"
    restart: always
    ports: 
      - "5432:5432"
    volumes:
      - database-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
  
  redis:
    # image: "redis:6.2.3-alpine"
    image: "myredis"
    container_name: "myredis"
    restart: on-failure 
    command: /bin/sh -c redis-server /user/local/etc/redis/redis.conf 
    ports:
      - 6379:6379
    # expose:
    #   - 6379
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    deploy:
      resources:
        limits:
          memory: 1G

volumes: 
  database-data:
  # redis-data:

# networks:
#   external:
#     web-service
