version: '3'

services:

  web:
    container_name: web
    build: ./django_site
    restart: always
    env_file:
      - .env
    entrypoint: /app/entrypoint.sh
    command: uwsgi --ini uwsgi.ini
    # ports:
    #   - "8000:8080"
    volumes:
      - ./django_site:/app
    depends_on:
      - db

  db:
    image: "postgres:14.2-alpine"
    container_name: "db"
    restart: always
    ports: 
      - "5432:5432"
    volumes:
      - database-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
  
  redis:
    # image: "redis:6.2.3-alpine"
    image: "myredis"
    container_name: "myredis"
    restart: on-failure 
    command: /bin/sh -c redis-server /user/local/etc/redis/redis.conf 
    ports:
      - 6379:6379
    # expose:
    #   - 6379
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    deploy:
      resources:
        limits:
          memory: 1G

  nginx:
    container_name: nginx
    build: ./nginx
    restart: always
    volumes:
      - static:/static
      - ./log:/var/log/nginx
    ports:
      - "8080:80"
    depends_on:
      - web

volumes: 
  database-data:
  static:
  # redis-data:

# networks:
#   default:
#     external:
#       name: web-service
