FROM python:3.9-slim-buster

RUN pip install --upgrade pip
RUN apt-get update
RUN apt-get install -y gcc

WORKDIR /tmp_dir
COPY backend/docker/requirements.txt /tmp_dir
RUN pip install -r requirements.txt
