version: '3'

services:
  redis:
    # image: "redis:6.2.3-alpine"
    image: "myredis"
    container_name: "myredis"
    restart: on-failure 
    command: /bin/sh -c redis-server /user/local/etc/redis/redis.conf 
    ports:
      - 6379:6379
    # expose:
    #   - 6379
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    deploy:
      resources:
        limits:
          memory: 1G